# Generated by Django 3.0.5 on 2020-06-14 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='Add',
        ),
    ]
